###
GET http://localhost:3000/api/employes

###
post http://localhost:3000/api/employes
content-type: application/json

{
    "name": "Morak",
    "position" : "sr.dev",
    "office": "Develps",
    "salary": "100000"
}

###
GET http://localhost:3000/api/employes/67d1baeaea681e21ac0981ed

###
DELETE http://localhost:3000/api/employes/67d1baf1ea681e21ac0981ef

###
PUT http://localhost:3000/api/employes/67d1baeaea681e21ac0981ed
content-type: application/json

{
    "position" : "CEO",
    "name": "OtakV23"
}

###
GET http://localhost:3000/api/parametros
###
POST http://localhost:3000/api/parametros
content-type: application/json

{
    "backgroundColor" :{
        "name": "Palido",
        "value": "#B5A8D5"
    },
    "textColor": {
        "name": "violento",
        "value": "#211C84"
    },
    "language" : {
        "name": "español",
        "code": "es"
    },
    "dark_mode": true,
    "name":"test"
}

###
PUT http://localhost:3000/api/parametros/67e4aedd620a5af32fc2856b
content-type: application/json

{
    "textColor": {
      "name": "violento",
      "value": "#3BD4A1"
    },
    "backgroundNavbar": {
      "name": "oscuro",
      "value": "#4D55CC"
    }
}

###
GET http://localhost:3000/api/clientes

###
POST http://localhost:3000/api/clientes
content-type: application/json

{
    "cod_cliente": "51241",
    "name":"Ludmila",
    "phone": "3471100199",
    "address":{
        "street": "calle 1",
        "number": "123",
        "city": "Medellin",
        "state": "Antioquia"
    },
    "documentType":"DNI",
    "documentNumber":"45222999",
    "notes":"Cargado desde el apiRest"
}